paths:
  jquery: 'lib/jquery-1.11.0.min'
  jquery_ujs: 'lib/rails'
  react: 'lib/react-with-addons-0.9.0'
  showdown: 'lib/showdown.min'
  backbone: 'lib/backbone-min'
  'backbone.relational': 'lib/backbone-relational'
  underscore: 'lib/underscore-min'
  blog: 'blog'

# shim non-amd libraries
shim:
  backbone:
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  'backbone.relational':
    deps: ['backbone']
  underscore:
    exports: '_'
  jquery_ujs:
    deps: ['jquery']
